language: ruby
before_script: sudo apt-get update && sudo apt-get install git
script: bundle exec rake test[all]
after_success: bundle exec rake publish_build BUILD_TYPE=release
env:
  global:
  - S3_BUCKET_NAME=builds.dockyard.com
  - S3_FILE_PREFIX=ember-validations
